version: '3'

networks:
  nodenet:
    driver: bridge

services:
  nginx:
    build:
      context: Nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - nodeserver

  nodeserver:
    build: 
      context: Node
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks:
      - nodenet
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: 
      context: Mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./Mysql/Data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet